version: '3.8'

services:
  gateway:
    build: 
      context: .
      dockerfile: api_gateway/Dockerfile
    ports:
      - "5000:5000"

  preprocessor-service:
    build: 
      context: .
      dockerfile: model_cleaning/Dockerfile
    ports:
      - "5001:5001"

  prediction-service:
    build: 
      context: .
      dockerfile: model_training/Dockerfile
    ports:
      - "5002:5002"